name:        mutable-containers
version:     0.3.4
synopsis:    Abstactions and concrete implementations of mutable containers
description: See docs and README at <http://www.stackage.org/package/mutable-containers>
category:    Data
author:      Michael Snoyman
maintainer:  michael@fpcomplete.com
license:     MIT
github:      snoyberg/mono-traversable

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.13 && <5
- containers
- vector

library:
  ghc-options: -O2
  source-dirs: src
  exposed-modules:
  - Data.Mutable
  dependencies:
  - primitive >=0.5.2.1
  - mono-traversable
  - ghc-prim
tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - mutable-containers
    - hspec
    - QuickCheck
    - primitive
benchmarks:
  deque:
    main: deque.hs
    source-dirs: bench
    ghc-options:
    - -Wall
    - -O2
    - -rtsopts
    dependencies:
    - mutable-containers
    - gauge
  ref:
    main: ref.hs
    source-dirs: bench
    ghc-options:
    - -Wall
    - -O2
    - -rtsopts
    dependencies:
    - mutable-containers
    - gauge
