name:        mono-traversable
version:     1.1.0.0
synopsis:    Type classes for mapping, folding, and traversing monomorphic containers
description: Please see the README at <https://www.stackage.org/package/mono-traversable>
category:    Data
author:      Michael Snoyman, John Wiegley, Greg Weber
maintainer:  michael@snoyman.com
license:     MIT
github:      snoyberg/mono-traversable

extra-source-files:
- README.md
- ChangeLog.md

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - base >= 4.13 && <5
  - containers >=0.5.8
  - unordered-containers >=0.2
  - hashable
  - bytestring >=0.9
  - text >=0.11
  - transformers >=0.3
  - vector >=0.10
  - vector-algorithms >=0.6
  - split >=0.2
tests:
  test:
    main: Main.hs
    source-dirs: test
    ghc-options: -O0
    dependencies:
    - base
    - mono-traversable
    - bytestring
    - text
    - hspec
    - HUnit
    - transformers
    - vector
    - QuickCheck
    - containers
    - unordered-containers
    - foldl
    build-tools: hspec-discover
benchmarks:
  all:
    main: main.hs
    source-dirs: bench
    ghc-options:
    - -Wall
    - -O2
    - -with-rtsopts=-A32m
    when:
      - condition: impl(ghc >= 8.6)
        ghc-options: -fproc-alignment=64
    dependencies:
    - base
    - gauge
    - mono-traversable
    - text
    - containers
    - bytestring
    - vector
    - mwc-random
    - deepseq
