name:        mono-traversable
version:     1.0.6.0
synopsis:    Type classes for mapping, folding, and traversing monomorphic containers
description: Please see the README at <https://www.stackage.org/package/mono-traversable>
category:    Data
author:      Michael Snoyman, John Wiegley, Greg Weber
maintainer:  michael@snoyman.com
license:     MIT
github:      snoyberg/mono-traversable

extra-source-files:
- README.md
- ChangeLog.md

library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - base >=4.7 && <5
  - containers >=0.4
  - unordered-containers >=0.2
  - hashable
  - bytestring >=0.9
  - text >=0.11
  - transformers >=0.3
  - vector >=0.10
  - vector-algorithms >=0.6
  - split >=0.2
  when:
  - condition: impl(ghc <8.0)
    dependencies:
    - semigroups >=0.10
tests:
  test:
    main: main.hs
    source-dirs: test
    ghc-options: -O0
    dependencies:
    - base
    - mono-traversable
    - bytestring
    - text
    - hspec
    - HUnit
    - transformers
    - vector
    - QuickCheck
    - semigroups
    - containers
    - unordered-containers
    - foldl
benchmarks:
  sorting:
    main: sorting.hs
    source-dirs: bench
    ghc-options:
    - -Wall
    - -O2
    dependencies:
    - base
    - criterion
    - mono-traversable
    - vector
    - mwc-random
